//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.19 at 01:00:49 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://fsrar.ru/WEGAIS/TTNSingle_v2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.fsrar.wegais.ttnsingle_v2;
