//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.06 at 02:52:09 PM MSK 
//


package io.secundus.model.xml

import ru.fsrar.wegais.actchargeon.*
import ru.fsrar.wegais.actinventoryabinfo.InformARegType
import ru.fsrar.wegais.actinventoryabinfo.InformBTypeRegItem
import ru.fsrar.wegais.actinventoryinformbreg.ActInventoryInformBReg
import ru.fsrar.wegais.actinventoryinformbreg.InformInvBRegItem
import ru.fsrar.wegais.actinventoryinformbreg.InformInvPositionType
import ru.fsrar.wegais.actinventorysingle.ActInventoryPositionType
import ru.fsrar.wegais.actinventorysingle.ActInventoryType
import ru.fsrar.wegais.actwriteoff.ActWriteOffPositionType
import ru.fsrar.wegais.actwriteoff.ActWriteOffType
import ru.fsrar.wegais.clientref.*
import ru.fsrar.wegais.productref.*
import ru.fsrar.wegais.queryformab.QueryFormAB
import ru.fsrar.wegais.queryparameters.Parameter
import ru.fsrar.wegais.queryparameters.QueryParameters
import ru.fsrar.wegais.replyap.ReplyAP
import ru.fsrar.wegais.replyclient.ReplyClient
import ru.fsrar.wegais.replyforma.ReplyFormA
import ru.fsrar.wegais.replyformb.ReplyFormB
import ru.fsrar.wegais.replyhistformb.OperationBType
import ru.fsrar.wegais.replyhistformb.ReplyHistFormB
import ru.fsrar.wegais.replyrests.ReplyRests
import ru.fsrar.wegais.replyrests.StockPositionType
import ru.fsrar.wegais.replyspirit.ReplySpirit
import ru.fsrar.wegais.replyssp.ReplySSP
import ru.fsrar.wegais.ticket.OperationResultType
import ru.fsrar.wegais.ticket.TicketResultType
import ru.fsrar.wegais.ticket.TicketType
import ru.fsrar.wegais.ttninformbreg.InformBPositionType
import ru.fsrar.wegais.ttninformbreg.WayBillInformBRegType
import ru.fsrar.wegais.ttnsingle.PositionType
import ru.fsrar.wegais.ttnsingle.TransportType
import ru.fsrar.wegais.ttnsingle.WayBillType
import ru.fsrar.wegais.wb_doc_single_01.DocBody
import ru.fsrar.wegais.wb_doc_single_01.Documents
import ru.fsrar.wegais.wb_doc_single_01.SenderInfo
import javax.xml.bind.JAXBElement
import javax.xml.bind.annotation.XmlElementDecl
import javax.xml.bind.annotation.XmlRegistry
import javax.xml.namespace.QName


/**
 * Файл пересоздан вручную из сгенерированного cjx для схемы 1
 *
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the io.secundus.model.xml package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
open class ObjectFactoryV1 {

    /**
     * Create an instance of [ReplyHistFormB]
     */
    fun createReplyHistFormB(): ReplyHistFormB {
        return ReplyHistFormB()
    }

    /**
     * Create an instance of [ReplyRests]
     */
    fun createReplyRests(): ReplyRests {
        return ReplyRests()
    }

    /**
     * Create an instance of [ReplyAP]
     */
    fun createReplyAP(): ReplyAP {
        return ReplyAP()
    }

    /**
     * Create an instance of [ReplyClient]
     */
    fun createReplyClient(): ReplyClient {
        return ReplyClient()
    }

    /**
     * Create an instance of [ReplySpirit]
     */
    fun createReplySpirit(): ReplySpirit {
        return ReplySpirit()
    }

    /**
     * Create an instance of [ReplySSP]
     */
    fun createReplySSP(): ReplySSP {
        return ReplySSP()
    }

    /**
     * Create an instance of [ActWriteOffType]
     */
    fun createActWriteOffType(): ActWriteOffType {
        return ActWriteOffType()
    }

    /**
     * Create an instance of [WayBillInformBRegType]
     */
    fun createWayBillInformBRegType(): WayBillInformBRegType {
        return WayBillInformBRegType()
    }

    /**
     * Create an instance of [QueryParameters]
     */
    fun createQueryParameters(): QueryParameters {
        return QueryParameters()
    }

    /**
     * Create an instance of [InformInvPositionType]
     */
    fun createInformInvPositionType(): InformInvPositionType {
        return InformInvPositionType()
    }

    /**
     * Create an instance of [ActInventoryInformBReg]
     */
    fun createActInventoryInformBReg(): ActInventoryInformBReg {
        return ActInventoryInformBReg()
    }

    /**
     * Create an instance of [ActChargeOnType]
     */
    fun createActChargeOnType(): ActChargeOnType {
        return ActChargeOnType()
    }

    /**
     * Create an instance of [ActChargeOnPositionType]
     */
    fun createActChargeOnPositionType(): ActChargeOnPositionType {
        return ActChargeOnPositionType()
    }

    /**
     * Create an instance of [ActInventoryPositionType]
     */
    fun createActInventoryPositionType(): ActInventoryPositionType {
        return ActInventoryPositionType()
    }

    /**
     * Create an instance of [ActInventoryType]
     */
    fun createActInventoryType(): ActInventoryType {
        return ActInventoryType()
    }

    /**
     * Create an instance of [WayBillType]
     */
    fun createWayBillType(): WayBillType {
        return WayBillType()
    }

    /**
     * Create an instance of [MarkInfoType]
     */
    fun createMarkInfoType(): MarkInfoType {
        return MarkInfoType()
    }

    /**
     * Create an instance of [MarkInfoType.Ranges]
     */
    fun createMarkInfoTypeRanges(): MarkInfoType.Ranges {
        return MarkInfoType.Ranges()
    }

    /**
     * Create an instance of [OrgInfoEx]
     */
    fun createOrgInfoEx(): OrgInfoEx {
        return OrgInfoEx()
    }

    /**
     * Create an instance of [Documents]
     */
    fun createDocuments(): Documents {
        return Documents()
    }

    /**
     * Create an instance of [SenderInfo]
     */
    fun createSenderInfo(): SenderInfo {
        return SenderInfo()
    }

    /**
     * Create an instance of [DocBody]
     */
    fun createDocBody(): DocBody {
        return DocBody()
    }

    /**
     * Create an instance of [OrgLicenseType]
     */
    fun createOrgLicenseType(): OrgLicenseType {
        return OrgLicenseType()
    }

    /**
     * Create an instance of [OrgInfo]
     */
    fun createOrgInfo(): OrgInfo {
        return OrgInfo()
    }

    /**
     * Create an instance of [ProductContractType]
     */
    fun createProductContractType(): ProductContractType {
        return ProductContractType()
    }

    /**
     * Create an instance of [OrganizationsType]
     */
    fun createOrganizationsType(): OrganizationsType {
        return OrganizationsType()
    }

    /**
     * Create an instance of [OrgItemType]
     */
    fun createOrgItemType(): OrgItemType {
        return OrgItemType()
    }

    /**
     * Create an instance of [OrgAddressType]
     */
    fun createOrgAddressType(): OrgAddressType {
        return OrgAddressType()
    }

    /**
     * Create an instance of [ProductsType]
     */
    fun createProductsType(): ProductsType {
        return ProductsType()
    }

    /**
     * Create an instance of [ProductInfo]
     */
    fun createProductInfo(): ProductInfo {
        return ProductInfo()
    }

    /**
     * Create an instance of [InformBTypeItem]
     */
    fun createInformBTypeItem(): InformBTypeItem {
        return InformBTypeItem()
    }

    /**
     * Create an instance of [InformAType]
     */
    fun createInformAType(): InformAType {
        return InformAType()
    }

    /**
     * Create an instance of [InformBType]
     */
    fun createInformBType(): InformBType {
        return InformBType()
    }

    /**
     * Create an instance of [PositionType]
     */
    fun createPositionType(): PositionType {
        return PositionType()
    }

    /**
     * Create an instance of [TransportType]
     */
    fun createTransportType(): TransportType {
        return TransportType()
    }

    /**
     * Create an instance of [TicketResultType]
     */
    fun createTicketResultType(): TicketResultType {
        return TicketResultType()
    }

    /**
     * Create an instance of [OperationResultType]
     */
    fun createOperationResultType(): OperationResultType {
        return OperationResultType()
    }

    /**
     * Create an instance of [TicketType]
     */
    fun createTicketType(): TicketType {
        return TicketType()
    }

    /**
     * Create an instance of [InformBTypeRegItem]
     */
    fun createInformBTypeRegItem(): InformBTypeRegItem {
        return InformBTypeRegItem()
    }

    /**
     * Create an instance of [InformARegType]
     */
    fun createInformARegType(): InformARegType {
        return InformARegType()
    }

    /**
     * Create an instance of [MarkCodeInfoType]
     */
    fun createMarkCodeInfoType(): MarkCodeInfoType {
        return MarkCodeInfoType()
    }

    /**
     * Create an instance of [InformABRegType]
     */
    fun createInformABRegType(): InformABRegType {
        return InformABRegType()
    }

    /**
     * Create an instance of [InformABKeyType]
     */
    fun createInformABKeyType(): InformABKeyType {
        return InformABKeyType()
    }

    /**
     * Create an instance of [InformInvBRegItem]
     */
    fun createInformInvBRegItem(): InformInvBRegItem {
        return InformInvBRegItem()
    }

    /**
     * Create an instance of [Parameter]
     */
    fun createParameter(): Parameter {
        return Parameter()
    }

    /**
     * Create an instance of [QueryFormAB]
     */
    fun createQueryFormAB(): QueryFormAB {
        return QueryFormAB()
    }

    /**
     * Create an instance of [InformBPositionType]
     */
    fun createInformBPositionType(): InformBPositionType {
        return InformBPositionType()
    }

    /**
     * Create an instance of [ActWriteOffPositionType]
     */
    fun createActWriteOffPositionType(): ActWriteOffPositionType {
        return ActWriteOffPositionType()
    }

    /**
     * Create an instance of [StockPositionType]
     */
    fun createStockPositionType(): StockPositionType {
        return StockPositionType()
    }

    /**
     * Create an instance of [ReplyFormA]
     */
    fun createReplyFormA(): ReplyFormA {
        return ReplyFormA()
    }

    /**
     * Create an instance of [ReplyFormB]
     */
    fun createReplyFormB(): ReplyFormB {
        return ReplyFormB()
    }

    /**
     * Create an instance of [OperationBType]
     */
    fun createOperationBType(): OperationBType {
        return OperationBType()
    }

    /**
     * Create an instance of [ReplyHistFormB.HistoryB]
     */
    fun createReplyHistFormBHistoryB(): ReplyHistFormB.HistoryB {
        return ReplyHistFormB.HistoryB()
    }

    /**
     * Create an instance of [ReplyRests.Products]
     */
    fun createReplyRestsProducts(): ReplyRests.Products {
        return ReplyRests.Products()
    }

    /**
     * Create an instance of [ReplyAP.Products]
     */
    fun createReplyAPProducts(): ReplyAP.Products {
        return ReplyAP.Products()
    }

    /**
     * Create an instance of [ReplyClient.Clients]
     */
    fun createReplyClientClients(): ReplyClient.Clients {
        return ReplyClient.Clients()
    }

    /**
     * Create an instance of [ReplySpirit.Products]
     */
    fun createReplySpiritProducts(): ReplySpirit.Products {
        return ReplySpirit.Products()
    }

    /**
     * Create an instance of [ReplySSP.Products]
     */
    fun createReplySSPProducts(): ReplySSP.Products {
        return ReplySSP.Products()
    }

    /**
     * Create an instance of [ActWriteOffType.Header]
     */
    fun createActWriteOffTypeHeader(): ActWriteOffType.Header {
        return ActWriteOffType.Header()
    }

    /**
     * Create an instance of [ActWriteOffType.Content]
     */
    fun createActWriteOffTypeContent(): ActWriteOffType.Content {
        return ActWriteOffType.Content()
    }

    /**
     * Create an instance of [WayBillInformBRegType.Header]
     */
    fun createWayBillInformBRegTypeHeader(): WayBillInformBRegType.Header {
        return WayBillInformBRegType.Header()
    }

    /**
     * Create an instance of [WayBillInformBRegType.Content]
     */
    fun createWayBillInformBRegTypeContent(): WayBillInformBRegType.Content {
        return WayBillInformBRegType.Content()
    }

    /**
     * Create an instance of [QueryParameters.Parameters]
     */
    fun createQueryParametersParameters(): QueryParameters.Parameters {
        return QueryParameters.Parameters()
    }

    /**
     * Create an instance of [InformInvPositionType.InformB]
     */
    fun createInformInvPositionTypeInformB(): InformInvPositionType.InformB {
        return InformInvPositionType.InformB()
    }

    /**
     * Create an instance of [ActInventoryInformBReg.Header]
     */
    fun createActInventoryInformBRegHeader(): ActInventoryInformBReg.Header {
        return ActInventoryInformBReg.Header()
    }

    /**
     * Create an instance of [ActInventoryInformBReg.Content]
     */
    fun createActInventoryInformBRegContent(): ActInventoryInformBReg.Content {
        return ActInventoryInformBReg.Content()
    }

    /**
     * Create an instance of [ActChargeOnType.Header]
     */
    fun createActChargeOnTypeHeader(): ActChargeOnType.Header {
        return ActChargeOnType.Header()
    }

    /**
     * Create an instance of [ActChargeOnType.Content]
     */
    fun createActChargeOnTypeContent(): ActChargeOnType.Content {
        return ActChargeOnType.Content()
    }

    /**
     * Create an instance of [ActChargeOnPositionType.InformAB]
     */
    fun createActChargeOnPositionTypeInformAB(): ActChargeOnPositionType.InformAB {
        return ActChargeOnPositionType.InformAB()
    }

    /**
     * Create an instance of [ActInventoryPositionType.InformB]
     */
    fun createActInventoryPositionTypeInformB(): ActInventoryPositionType.InformB {
        return ActInventoryPositionType.InformB()
    }

    /**
     * Create an instance of [ActInventoryType.Header]
     */
    fun createActInventoryTypeHeader(): ActInventoryType.Header {
        return ActInventoryType.Header()
    }

    /**
     * Create an instance of [ActInventoryType.Content]
     */
    fun createActInventoryTypeContent(): ActInventoryType.Content {
        return ActInventoryType.Content()
    }

    /**
     * Create an instance of [WayBillType.Header]
     */
    fun createWayBillTypeHeader(): WayBillType.Header {
        return WayBillType.Header()
    }

    /**
     * Create an instance of [WayBillType.Content]
     */
    fun createWayBillTypeContent(): WayBillType.Content {
        return WayBillType.Content()
    }

    /**
     * Create an instance of [MarkInfoType.Ranges.Range]
     */
    fun createMarkInfoTypeRangesRange(): MarkInfoType.Ranges.Range {
        return MarkInfoType.Ranges.Range()
    }

    /**
     * Create an instance of [OrgInfoEx.Addresslist]
     */
    fun createOrgInfoExAddresslist(): OrgInfoEx.Addresslist {
        return OrgInfoEx.Addresslist()
    }

    /**
     * Create an instance of [JAXBElement]`<`[String]`>`}
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef", name = "INN", scope = OrgInfoEx::class)
    fun createOrgInfoExINN(value: String): JAXBElement<String> {
        return JAXBElement(_OrgInfoExINN_QNAME, String::class.java, OrgInfoEx::class.java, value)
    }

    /**
     * Create an instance of [JAXBElement]`<`[String]`>`}
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef", name = "RNN", scope = OrgInfoEx::class)
    fun createOrgInfoExRNN(value: String): JAXBElement<String> {
        return JAXBElement(_OrgInfoExRNN_QNAME, String::class.java, OrgInfoEx::class.java, value)
    }

    /**
     * Create an instance of [JAXBElement]`<`[String]`>`}
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef", name = "UNP", scope = OrgInfoEx::class)
    fun createOrgInfoExUNP(value: String): JAXBElement<String> {
        return JAXBElement(_OrgInfoExUNP_QNAME, String::class.java, OrgInfoEx::class.java, value)
    }

    /**
     * Create an instance of [JAXBElement]`<`[String]`>`}
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef", name = "State", scope = OrgInfoEx::class)
    fun createOrgInfoExState(value: String): JAXBElement<String> {
        return JAXBElement(_OrgInfoExState_QNAME, String::class.java, OrgInfoEx::class.java, value)
    }

    /**
     * Create an instance of [JAXBElement]`<`[String]`>`}
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef", name = "INN", scope = OrgInfo::class)
    fun createOrgInfoINN(value: String): JAXBElement<String> {
        return JAXBElement(_OrgInfoExINN_QNAME, String::class.java, OrgInfo::class.java, value)
    }

    /**
     * Create an instance of [JAXBElement]`<`[String]`>`}
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef", name = "RNN", scope = OrgInfo::class)
    fun createOrgInfoRNN(value: String): JAXBElement<String> {
        return JAXBElement(_OrgInfoExRNN_QNAME, String::class.java, OrgInfo::class.java, value)
    }

    /**
     * Create an instance of [JAXBElement]`<`[String]`>`}
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef", name = "UNP", scope = OrgInfo::class)
    fun createOrgInfoUNP(value: String): JAXBElement<String> {
        return JAXBElement(_OrgInfoExUNP_QNAME, String::class.java, OrgInfo::class.java, value)
    }

    companion object {

        private val _OrgInfoExINN_QNAME = QName("http://fsrar.ru/WEGAIS/ClientRef", "INN")
        private val _OrgInfoExRNN_QNAME = QName("http://fsrar.ru/WEGAIS/ClientRef", "RNN")
        private val _OrgInfoExUNP_QNAME = QName("http://fsrar.ru/WEGAIS/ClientRef", "UNP")
        private val _OrgInfoExState_QNAME = QName("http://fsrar.ru/WEGAIS/ClientRef", "State")
    }
}
